spring:
  application:
    name: inventory-system
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: admin
    password: admin@123
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    web:
      pageable:
        max-page-size: 100

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
