ALTER TABLE users
    ALTER COLUMN first_name SET NOT NULL,
    ALTER COLUMN first_name TYPE VARCHAR(100),
    ALTER COLUMN last_name SET NOT NULL,
    ALTER COLUMN last_name TYPE VARCHAR(100),
    ALTER COLUMN email SET NOT NULL,
    ALTER COLUMN email TYPE VARCHAR(100),
    ALTER COLUMN password SET NOT NULL,
    ALTER COLUMN password TYPE VARCHAR(255),
    ALTER COLUMN phone_number TYPE VARCHAR(20),
    ALTER COLUMN gender TYPE VARCHAR(20),
    ALTER COLUMN city TYPE VARCHAR(100),
    ALTER COLUMN state TYPE VARCHAR(100),
    ALTER COLUMN country TYPE VARCHAR(100),
    ALTER COLUMN postal_code TYPE VARCHAR(20),
    ALTER COLUMN driving_license_number TYPE VARCHAR(50),
    ALTER COLUMN role SET NOT NULL,
    ALTER COLUMN role TYPE VARCHAR(50);

ALTER TABLE users
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP;
